// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO group_members (group_id, user_id, display_name)
VALUES ($1, $2, $3)
RETURNING group_id, user_id, display_name, created_at
`

type AddMemberParams struct {
	GroupID     pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.GroupID, arg.UserID, arg.DisplayName)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM group_members
WHERE group_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, group_id, paid_by, description, amount_cents, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, paid_by, description, amount_cents, currency, created_at
`

type CreateExpenseParams struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	PaidBy      pgtype.UUID
	Description string
	AmountCents int64
	Currency    string
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.GroupID,
		arg.PaidBy,
		arg.Description,
		arg.AmountCents,
		arg.Currency,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PaidBy,
		&i.Description,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createExpenseSplit = `-- name: CreateExpenseSplit :one
INSERT INTO expense_splits (expense_id, user_id, amount_cents)
VALUES ($1, $2, $3)
RETURNING expense_id, user_id, amount_cents
`

type CreateExpenseSplitParams struct {
	ExpenseID   pgtype.UUID
	UserID      pgtype.UUID
	AmountCents int64
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseSplit, arg.ExpenseID, arg.UserID, arg.AmountCents)
	var i ExpenseSplit
	err := row.Scan(&i.ExpenseID, &i.UserID, &i.AmountCents)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, created_by, created_at
`

type CreateGroupParams struct {
	ID        pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ID, arg.Name, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (id, group_id, from_user_id, to_user_id, amount_cents, settled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, from_user_id, to_user_id, amount_cents, settled_at, created_at
`

type CreateSettlementParams struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	FromUserID  pgtype.UUID
	ToUserID    pgtype.UUID
	AmountCents int64
	SettledAt   pgtype.Timestamptz
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.ID,
		arg.GroupID,
		arg.FromUserID,
		arg.ToUserID,
		arg.AmountCents,
		arg.SettledAt,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.AmountCents,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, created_at
`

type CreateUserParams struct {
	ID    pgtype.UUID
	Email string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteExpenseSplitsForMember = `-- name: DeleteExpenseSplitsForMember :exec
DELETE FROM expense_splits
WHERE user_id = $2
  AND expense_id IN (
    SELECT id FROM expenses WHERE group_id = $1
  )
`

type DeleteExpenseSplitsForMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) DeleteExpenseSplitsForMember(ctx context.Context, arg DeleteExpenseSplitsForMemberParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplitsForMember, arg.GroupID, arg.UserID)
	return err
}

const deleteExpensesPaidByMember = `-- name: DeleteExpensesPaidByMember :exec
DELETE FROM expenses
WHERE group_id = $1 AND paid_by = $2
`

type DeleteExpensesPaidByMemberParams struct {
	GroupID pgtype.UUID
	PaidBy  pgtype.UUID
}

func (q *Queries) DeleteExpensesPaidByMember(ctx context.Context, arg DeleteExpensesPaidByMemberParams) error {
	_, err := q.db.Exec(ctx, deleteExpensesPaidByMember, arg.GroupID, arg.PaidBy)
	return err
}

const deleteExpensesWithoutSplits = `-- name: DeleteExpensesWithoutSplits :exec
DELETE FROM expenses e
WHERE e.group_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM expense_splits s WHERE s.expense_id = e.id
  )
`

func (q *Queries) DeleteExpensesWithoutSplits(ctx context.Context, groupID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpensesWithoutSplits, groupID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteSettlementsForMember = `-- name: DeleteSettlementsForMember :exec
DELETE FROM settlements
WHERE group_id = $1 AND (from_user_id = $2 OR to_user_id = $2)
`

type DeleteSettlementsForMemberParams struct {
	GroupID    pgtype.UUID
	FromUserID pgtype.UUID
}

func (q *Queries) DeleteSettlementsForMember(ctx context.Context, arg DeleteSettlementsForMemberParams) error {
	_, err := q.db.Exec(ctx, deleteSettlementsForMember, arg.GroupID, arg.FromUserID)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_by, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT group_id, user_id, display_name, created_at
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenseSplits = `-- name: ListExpenseSplits :many
SELECT
  s.expense_id,
  s.user_id,
  member.display_name,
  s.amount_cents
FROM expense_splits s
JOIN expenses e ON e.id = s.expense_id
JOIN group_members member ON member.group_id = e.group_id AND member.user_id = s.user_id
WHERE e.group_id = $1
ORDER BY s.expense_id, member.created_at ASC
`

type ListExpenseSplitsRow struct {
	ExpenseID   pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	AmountCents int64
}

func (q *Queries) ListExpenseSplits(ctx context.Context, groupID pgtype.UUID) ([]ListExpenseSplitsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplits, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsRow
	for rows.Next() {
		var i ListExpenseSplitsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.UserID,
			&i.DisplayName,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT
  e.id,
  e.group_id,
  e.paid_by,
  payer.display_name AS paid_by_name,
  e.description,
  e.amount_cents,
  e.currency,
  e.created_at
FROM expenses e
JOIN group_members payer ON payer.group_id = e.group_id AND payer.user_id = e.paid_by
WHERE e.group_id = $1
ORDER BY e.created_at DESC
`

type ListExpensesRow struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	PaidBy      pgtype.UUID
	PaidByName  string
	Description string
	AmountCents int64
	Currency    string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListExpenses(ctx context.Context, groupID pgtype.UUID) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesRow
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PaidBy,
			&i.PaidByName,
			&i.Description,
			&i.AmountCents,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, created_by, created_at
FROM groups
ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT group_id, user_id, display_name, created_at
FROM group_members
WHERE group_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlements = `-- name: ListSettlements :many
SELECT
  s.id,
  s.group_id,
  s.from_user_id,
  from_member.display_name AS from_name,
  s.to_user_id,
  to_member.display_name AS to_name,
  s.amount_cents,
  s.settled_at,
  s.created_at
FROM settlements s
JOIN group_members from_member ON from_member.group_id = s.group_id AND from_member.user_id = s.from_user_id
JOIN group_members to_member ON to_member.group_id = s.group_id AND to_member.user_id = s.to_user_id
WHERE s.group_id = $1
ORDER BY s.created_at DESC
`

type ListSettlementsRow struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	FromUserID  pgtype.UUID
	FromName    string
	ToUserID    pgtype.UUID
	ToName      string
	AmountCents int64
	SettledAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSettlements(ctx context.Context, groupID pgtype.UUID) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementsRow
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromUserID,
			&i.FromName,
			&i.ToUserID,
			&i.ToName,
			&i.AmountCents,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.GroupID, arg.UserID)
	return err
}
