// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	PaidBy      pgtype.UUID
	Description string
	AmountCents int64
	Currency    string
	CreatedAt   pgtype.Timestamptz
}

type ExpenseSplit struct {
	ExpenseID   pgtype.UUID
	UserID      pgtype.UUID
	AmountCents int64
}

type Group struct {
	ID        pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type GroupMember struct {
	GroupID     pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

type Settlement struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	FromUserID  pgtype.UUID
	ToUserID    pgtype.UUID
	AmountCents int64
	SettledAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	ExternalAuthID pgtype.Text
	Email          string
	CreatedAt      pgtype.Timestamptz
}
